### ISSUE TITLE
Support 9.1.1 Release

### ISSUE THREAD

**Issue by xf-** [1and1/debianized-sentry#6]
[edited]

We’ve just tagged v9.1.0 of Sentry, which is our intended final release of the 9.x series, and the last release which will support “mostly whatever infrastructure you want”. We’re hoping this will create a good cutover point for us to migrate off a ton of legacy functionality, which paves the way to some required changes (such as Python 3).

A summary of changes can be viewed here: https://github.com/getsentry/sentry/blob/9.1.0/CHANGES

**Comment by jhermann** [comment]
Provide an announcement link or some other context please

**Comment by xf-** [comment]
https://github.com/getsentry/sentry/releases

**Comment by jhermann** [comment]
Forums: “We’re tracking issues with 9.1 to publish a 9.1.1 release (hopefully next week)”

**Comment by jhermann** [comment]
https://github.com/getsentry/sentry/compare/9.1.0...9.1.1
